name: Install tools with asdf
description: Install tools using asdf with a cache

#asdf-vm version references git hash until v4 is properly released https://github.com/asdf-vm/actions/issues/594

runs:
  using: "composite"
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@9cd779f40fe38688dd19505ccbc4eaaf018b44e7
    - name: Cache .asdf directory
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.asdf
        key: asdf-${{ hashFiles('**/.tool-versions') }}
    - name: Install asdf tools
      if: steps.cache.outputs.cache-hit != 'true'
      uses: asdf-vm/actions/install@9cd779f40fe38688dd19505ccbc4eaaf018b44e7