"""
This type stub file was generated by pyright.
"""

import json
import sys
import sysconfig
import typing as tp
from pathlib import Path
from tfparse._tfparse import ffi

class TFMeta(tp.TypedDict):
    label: str
    filename: str

class VariableMeta(tp.TypedDict):
    __tfmeta: TFMeta
    type: str

class Parsed(tp.TypedDict):
    variable: tp.List[VariableMeta]

def load_from_path(
    filePath: str,
    stop_on_hcl_error: bool = False,
    debug: bool = False,
    allow_downloads: bool = False,
    workspace_name: str = "default",
    vars_paths: tp.List[str] | None = None,
) -> Parsed: ...
